Mattilsynet/designsystem

package.json
src/scss/_theme.scss
src/scss/components/_disclosure.scss
src/scss/components/_form.scss
src/scss/components/_list.scss
src/scss/global/_typography.scss
src/scss/utilities/_mixins.scss
src/svelte/Breadcrumbs.svelte
stories/Breadcrumbs.stories.svelte
stories/Disclosure.stories.svelte
stories/components/ErrorSummary.stories.svelte
stories/components/Links.stories.svelte
stories/visualStyle/Spacing.stories.svelte

Mt 215 spacing in accordion

---

src/scss/utilities/_layout.scss
src/ts/count-characters.ts
src/ts/types.d.ts
stories/TextArea.stories.svelte

Add character counter for input and textarea

---

package.json
src/scss/components/_form.scss
src/scss/utilities/_mixins.scss

Mt 310 safari focus

---

package-lock.json
package.json
src/scss/utilities/_layout.scss

- to be able to hide next blocks in form funnel
Relates to MT-277

Add display none class

---

src/scss/global/_links.scss

Fix alignment and lineheight on transport card

---

src/scss/_theme.scss
src/scss/components/_article.scss
src/scss/components/_breadcrumbs.scss
src/scss/components/_disclosure.scss
src/scss/components/_file-upload-button.scss
src/scss/components/_form-steps.scss
src/scss/components/_form.scss
src/scss/components/_image.scss
src/scss/components/_index.scss
src/scss/components/_list.scss
src/scss/components/_notice.scss
src/scss/components/_summary-details.scss
src/scss/global/_links.scss
src/scss/global/_typography.scss
src/scss/utilities/_layout.scss
src/scss/utilities/_mixins.scss
stories/components/Article.stories.svelte
stories/components/Buttons.stories.svelte
stories/components/Links.stories.svelte
stories/visualStyle/Colors.stories.svelte
stories/visualStyle/Typography.stories.svelte

MT 40 Update spacing

---

src/scss/_color-token-contrast.md
src/scss/_color-tokens.scss
src/scss/components/_index.scss
src/scss/components/_task.scss
src/scss/utilities/_mixins.scss
src/scss/utilities/colors.js
stories/components/content/Article.stories.svelte
stories/components/content/Task.stories.svelte

Add styling for task

---

src/scss/components/_form-intro.scss
src/scss/components/_index.scss
src/scss/components/_notice.scss
stories/components/content/FormIntro.stories.svelte

Add styling and story for form intro module

---

src/scss/components/_multipage-form.scss
src/scss/global/_typography.scss

Mt 169 fix spacing arround h1

---

.storybook/preview.js
README.md
stories/Breadcrumbs.stories.svelte
stories/Checkbox.stories.svelte
stories/Disclosure.stories.svelte
stories/FormSteps.stories.svelte
stories/Header.stories.svelte
stories/Input.stories.svelte
stories/RadioButtons.stories.svelte
stories/Select.stories.svelte
stories/SkipLink.stories.svelte
stories/TextArea.stories.svelte
stories/components/Buttons.stories.svelte
stories/components/ErrorSummary.stories.svelte
stories/components/Footer.stories.svelte
stories/components/Links.stories.svelte
stories/components/Notice.stories.svelte
stories/components/SummaryDetail.stories.svelte
stories/components/content/Article.stories.svelte
stories/components/content/FormIntro.stories.svelte
stories/components/content/FormIntroModule.stories.svelte
stories/components/content/LegalGuidance.stories.svelte
stories/components/content/LegalText.stories.svelte
stories/components/content/ProfessionalAdvice.stories.svelte
stories/components/content/Task.stories.svelte
stories/components/form/AllForm.stories.svelte
stories/visualStyle/Colors.stories.svelte
stories/visualStyle/Spacing.stories.svelte
stories/visualStyle/Typography.stories.svelte

Load styrbook css in preview.js

---

src/scss/components/_chapter-menu.scss
src/scss/components/_index.scss
src/scss/components/_list.scss
src/svelte/ChapterMenu.svelte
src/ts/utils.ts
stories/components/ChapterMenu.stories.svelte

Add Chapter Menu component

---

src/svelte/ChapterMenu.svelte
src/ts/types.d.ts

Expose types used by ChapterMenu

---

src/scss/components/_form.scss

Decrease spacing between inputs on mobile
Relates to MT-442

Mt 442 responsive form

---

src/scss/components/_disclosure.scss

Adjust padding accordion
Relates to MT-458

Mt 458 responsive accordion

---

src/scss/_theme.scss
src/scss/utilities/_layout.scss

Responsive header and footer
Relates to MT-449

Mt 449 responsive header footer

---

src/scss/components/_disclosure.scss
src/svelte/Disclosure.svelte

Also remove arrow icon when header is not a button, because it isn't useful in non-javascript environments.
Relates to: MT-552

Remove initial accordion animation

---

.storybook/main.js
src/scss/components/_breadcrumbs.scss
src/scss/components/_buttons.scss
src/scss/global/_links.scss
src/svelte/Breadcrumbs.svelte
src/ts/types.d.ts
stories/Breadcrumbs.stories.svelte
stories/components/Buttons.stories.svelte

MT-452: Collaps breadcrumbs if it is longer than 3 elements

---

src/scss/global/_typography.scss

Remove auto hyphens from heading

---

src/svelte/FileUploadButton.svelte
stories/components/Buttons.stories.svelte

- to file upload
Relates to MT-292

Add aria-required

---

src/svelte/Breadcrumbs.svelte

Change load js default to true

---

src/scss/components/_buttons.scss
src/scss/components/_disclosure.scss
src/svelte/Disclosure.svelte
stories/Disclosure.stories.svelte

Add "link"-theme to Disclosure

---

src/scss/components/_form-steps.scss
src/scss/utilities/_layout.scss
src/svelte/FormSteps.svelte
stories/FormSteps.stories.svelte

Responsive stepper

---

src/svelte/Disclosure.svelte
stories/Disclosure.stories.svelte

Add configurable classes to Disclosure

---

src/scss/_theme.scss
src/scss/utilities/_layout.scss

Add $breakpoint-x-large and $container-width

---

src/scss/components/_dropdown.scss
src/scss/utilities/_layout.scss
src/svelte/Dropdown.svelte
stories/Dropdown.stories.svelte
stories/Header.stories.svelte

MT-447: Update styling for dropdown

---

src/scss/components/_disclosure.scss
src/scss/global/_typography.scss
src/svelte/Disclosure.svelte
stories/Disclosure.stories.svelte

- bold and indentation for hover
- fix font-size bordered accordion
Relates to MT-546

MT-546 Feat Add hover style for bordered accordion

---

src/svelte/Breadcrumbs.svelte
stories/Breadcrumbs.stories.svelte

Fix reactivity on breadcrumbs

---

src/svelte/form/TextArea.svelte
src/svelte/form/TextInput.svelte
src/ts/count-characters.ts
stories/components/form/AllForm.stories.svelte
stories/components/form/Input.stories.svelte
stories/components/form/TextArea.stories.svelte

MT-553 Change hard coded phrase (x tegn igjen) to dynamic

---

src/svelte/form/FileUpload.svelte

MT-553: Add phrases to fileupload

---

src/scss/components/_disclosure.scss

- select only direct header of disclosure-links
MT-620

Fix disclosure inside disclosure link

---

src/scss/components/_article.scss
stories/components/content/Article.stories.svelte
stories/components/content/LegalGuidance.stories.svelte
stories/components/content/ProfessionalAdvice.stories.svelte

- for moved under intro
MT-376

MT-376: Update published style

---

src/scss/utilities/_layout.scss
src/svelte/FileUploadButton.svelte

MT-385:Fix file upload scroll

---

src/scss/_color-token-contrast.md
src/scss/_color-tokens.scss
src/scss/components/_index.scss
src/scss/components/_top-tasks.scss
src/scss/global/_index.scss
src/scss/global/_links.scss
src/scss/global/_utils.scss
src/scss/utilities/_layout.scss
src/scss/utilities/colors.js
stories/components/Links.stories.svelte
stories/components/content/TopTasks.stories.svelte

Add styling for toppoppgave
MT-655

MT-655: Add top task

---

.storybook/main.js
package.json

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag

Fix deprecated static-dir flag waring

---

.github/workflows/main.yml
.prettierrc
src/scss/components/_index.scss
src/scss/components/_status.scss
src/svelte/Status.svelte
src/svelte/Status.test.ts
src/ts/utils.ts
stories/components/content/Status.stories.svelte

Mt-591: status component

---

src/scss/global/_links.scss
src/svelte/HighlightedContentLink.svelte
src/svelte/HighlightedContentLink.test.ts
src/svelte/Published.svelte
src/svelte/Published.test.ts
src/ts/utils.ts
stories/components/HighlightedContentLink.stories.svelte

Add component and styling for highlighted content
MT-650

MT-650: hightlighted content

---

src/ts/utils.ts

Remove duplicate function
MT-650

MT-650: fix for highlighted content

---

src/scss/components/_top-tasks.scss

MT-655: Fix spacing layout

---

src/svelte/content/AnimalDisease.svelte
src/svelte/content/AnimalDisease.test.ts

Fix not render text when undefined
MT-644

MT-644: Animal disease

---

src/scss/_color-token-contrast.md
src/scss/_color-tokens.scss
src/scss/components/_top-tasks.scss
src/scss/global/_utils.scss
src/scss/utilities/_grid.scss
src/scss/utilities/_layout.scss
src/scss/utilities/colors.js

- 2 column layout
- 1 column cetered layout
- add colors
MT-649

MT-649: layout

---

src/scss/global/_links.scss
src/svelte/content/RelatedLinksList.svelte
src/svelte/content/RelatedLinksList.test.ts
stories/components/Links.stories.svelte
stories/components/content/RelatedLinksList.stories.svelte

- new link style for custom link list
MT-663

MT-663: Add forward arrow end link

---

src/svelte/Status.svelte
src/svelte/Status.test.ts

MT-691:Add check to only show date when status type important

---

src/scss/components/_status.scss
src/svelte/Status.svelte
stories/components/content/Status.stories.svelte

MT-693:Status - Fix spacing text

---

src/scss/global/_links.scss
stories/components/content/TopTasks.stories.svelte

MT-694: Fix single wrapping arrow

---

src/scss/components/_article.scss
src/scss/components/_status.scss
src/svelte/Published.svelte
src/svelte/Status.svelte
src/svelte/Status.test.ts

MT-697: Status-Add text to updated date

---

src/scss/components/_article.scss

- to use on themepage part
Mt-633

MT-633:Theme page - Add class to for full width

---

src/svelte/content/RelatedLinksList.svelte
src/svelte/content/RelatedLinksList.test.ts

MT-730: Fix 500 on custom link list

---

src/scss/components/_article.scss
src/svelte/Published.svelte

MT-725: Fix order of dt and dd element in dl

---

src/svelte/content/RelatedLinksList.svelte

Mt-730: Fix build error

---

src/svelte/Breadcrumbs.svelte
src/svelte/CardArticle.svelte
src/svelte/Disclosure.svelte
src/svelte/Dropdown.svelte
src/svelte/content/RelatedLinksList.svelte
stories/Disclosure.stories.svelte
stories/components/Links.stories.svelte
stories/components/SummaryDetail.stories.svelte
stories/components/content/TopTasks.stories.svelte

MT-676: add support for html encoded characters

---

src/scss/components/_index.scss
src/scss/components/_video.scss

MT-689: Add styling for responsive video

---

src/scss/components/_disclosure.scss
src/svelte/Disclosure.svelte
stories/Disclosure.stories.svelte
stories/components/content/LegalText.stories.svelte

MT-733: Add styling for legal text disclosure

---

src/svelte/HighlightedContentLink.svelte
src/svelte/HighlightedContentLink.test.ts

MT-726: Make header optional between h2 or h3

---

src/scss/components/_article.scss
stories/components/content/LegalGuidance.stories.svelte

Fix: MT-740 - update legal guidance

---

src/scss/components/_article.scss
src/scss/components/_legal-collection.scss
src/scss/utilities/_mixins.scss

and reused the mixin inside legal-collection class

Created mixin article-spacing for styles in the article-page class

---

package-lock.json
package.json
src/scss/components/_article.scss
src/svelte/Published.svelte
src/svelte/Published.test.ts
src/svelte/Status.test.ts
src/svelte/content/RelatedLinksList.svelte
src/ts/utils.ts
stories/components/Published.stories.svelte
stories/components/content/Status.stories.svelte

MT-832: update updated date

---

src/svelte/Published.test.ts
src/ts/utils.ts

MT-832: Fix compare date

---

src/ts/utils.ts

MT-832: Change imports

---

package-lock.json
package.json
src/ts/utils.ts

- create own function to compare dates
MT-832

MT-832: Remove date-fns

---

src/scss/global/_links.scss
src/svelte/Breadcrumbs.svelte

🐛 MT-689: Move the three dots in the breadcrumbs

---

src/scss/components/_article.scss
src/scss/components/_legal-collection.scss
src/scss/utilities/_mixins.scss
stories/components/content/LegalGuidanceCollection.stories.svelte

the summary details needs less space on top and bottom.

💄 MT-891  Moved style out of the article-spacing mixin

---

src/scss/_color-token-contrast.md
src/scss/_color-tokens.scss
src/scss/_theme.scss
src/scss/components/_buttons.scss
src/scss/components/_disclosure.scss
src/scss/components/_file-upload-button.scss
src/scss/components/_form.scss
src/scss/components/_summary-details.scss
src/scss/global/_body.scss
src/scss/global/_links.scss
src/scss/utilities/_mixins.scss
src/scss/utilities/colors.js

Update focus color contrast
MT-834

♿️ MT-834 focus color contrast

---

src/scss/components/_notice.scss
src/svelte/Notice.svelte
stories/components/Notice.stories.svelte

💄 MT-759: Make notice content smaller on smaller screens

---

src/svelte/Dropdown.svelte
src/ts/click-outside.ts
src/ts/count-characters.ts
stories/Dropdown.stories.svelte

MT-666: Close drop down when clicks outside dropdown is registered

---

src/scss/components/_top-tasks.scss
src/scss/utilities/_grid.scss
stories/components/content/TopTasks.stories.svelte

💄 MT-828: Set max length for better readablility

---

src/scss/utilities/_mixins.scss
stories/components/content/LegalGuidanceCollection.stories.svelte

[MT-886](https://itemtest.atlassian.net/browse/MT-886)

Mt 886 spacing accordion

---

src/scss/global/_links.scss
src/scss/utilities/_mixins.scss
src/svelte/SummaryDetail.svelte

♿️ MT-843 focus same thickness links and btns

---

src/scss/global/_links.scss

- remove underline on links
- remover underline in linklist AND add indent
[MT-731](https://itemtest.atlassian.net/browse/MT-731)

MT-731 Removed underline when hovering a link

---

src/scss/components/_legal-collection.scss

- desktop “spacer-large” on margin-top
- mobile “--spacer-medium” on margin-tip
[MT-937](https://itemtest.atlassian.net/browse/MT-937)

💄 MT-937 Made spcases top/bottom between sections the same.

---

src/scss/utilities/_mixins.scss
src/svelte/CardArticle.svelte
stories/components/content/LegalGuidanceCollection.stories.svelte

- updated LegalGuidanceCollection story accordingly
see comment [MT-882](https://itemtest.atlassian.net/browse/MT-882)

MT-882 Dont add styling to h4 tag on CardArticle component

---

src/scss/global/_links.scss
stories/components/Links.stories.svelte

[MT-731](https://itemtest.atlassian.net/browse/MT-731)

🐛  Mt 731 animate double line links

---

src/svelte/form/TextArea.svelte
src/svelte/form/TextArea.test.ts
src/svelte/form/TextInput.svelte
src/svelte/form/TextInput.test.ts
src/ts/count-characters.ts
src/ts/utils.ts
stories/components/form/Input.stories.svelte

- to inform screenreaders about characters left
MT-499

♿ MT-499: Add aria-describedby and aria-live

---

src/scss/components/_dropdown.scss
src/scss/utilities/_layout.scss
src/svelte/Dropdown.svelte
stories/Header.stories.svelte

[MT-969](https://itemtest.atlassian.net/browse/MT-969)

⚡  Mt 969 header styling

---

src/scss/global/_links.scss
src/svelte/Link.svelte
src/svelte/Link.test.ts
src/ts/utils.test.ts
src/ts/utils.ts
stories/components/Links.stories.svelte

✨MT-1027: Link Component

---

src/scss/components/_animal-disease.scss
src/svelte/content/AnimalDisease.svelte
stories/components/content/AnimalDisease.stories.svelte

💄 MT-760 Fix spacing in text animal disease

---

package-lock.json
src/svelte/HighlightedContentLink.svelte
src/svelte/Published.svelte
src/svelte/Status.svelte
src/ts/utils.ts

🐛 Fixed tests where date was not formatted properly

---

src/scss/global/_utils.scss

🐛 MT-834: Remove not needed util class

---

src/scss/utilities/_grid.scss

💄MT-922 Add more grid col variations

---

src/scss/components/_article.scss

Decrease spacing published on mobile

💄MT-971 spacing published

---

src/scss/components/_disclosure.scss

💄MT-701 Update styling for open accordion

---

src/scss/global/_links.scss

💄 MT-722 Add hover effect to highlighted content

---

src/svelte/content/RelatedLinksList.svelte
src/svelte/content/RelatedLinksList.test.ts

🐛 MT-1041 dont show group title if linklist is empty

---

src/scss/components/_breadcrumbs.scss

💄MT-945 Fix same spacing on mobile and desktop

---

src/scss/components/_disclosure.scss
src/scss/components/_report.scss
src/scss/global/_links.scss
src/scss/global/_utils.scss
src/svelte/Link.svelte
stories/components/Links.stories.svelte
stories/components/content/Report.stories.svelte
stories/components/content/ReportSeries.stories.svelte

Update styling on report and report series

💄MT-1026 report styling

---

src/scss/components/_article.scss
src/scss/components/_summary-details.scss
src/scss/global/_typography.scss
src/svelte/CardArticle.svelte
src/svelte/CardArticle.test.ts
src/svelte/Disclosure.svelte
src/svelte/Disclosure.test.ts
src/svelte/HeadingLevel.svelte
src/svelte/HighlightedContentLink.svelte
src/svelte/SummaryDetail.svelte
stories/Disclosure.stories.svelte
stories/components/SummaryDetail.stories.svelte

Updates to be able to adjust heading levels from parent content
MT-1074

♿️ MT-1074 headings adjustment

---

src/svelte/Dropdown.svelte
src/svelte/FormSteps.svelte
src/svelte/form/RadioGroup.svelte
src/svelte/form/RadioGroup.test.ts
src/svelte/form/Select.svelte
src/svelte/form/TextArea.svelte
src/svelte/form/TextInput.svelte
src/ts/utils.ts

♿️ MT-909 fix cypress a11y

---

src/scss/components/_article.scss
src/scss/global/_links.scss
src/scss/utilities/_mixins.scss
stories/components/Links.stories.svelte

💄MT-763 table of contents

---

src/scss/components/_table.scss
stories/components/Table.stories.svelte

Fix caption styling
Fix extra space top in cell
MT-476

💄MT-476 table fix

---

src/scss/components/_dropdown.scss
src/svelte/Dropdown.svelte
src/svelte/content/MenuItems.svelte
stories/Header.stories.svelte

Update dropdown to show details summary for server rendered (no js)
MT-924

MT-924 dropdown pwa

---

src/scss/components/_dropdown.scss

💄MT-1171 Fix color on lines menu

---

src/scss/_theme.scss
src/scss/components/_disclosure.scss
src/scss/global/_body.scss
src/scss/global/_links.scss

💄MT-1170 Fix arrow sizing mobile

---

package-lock.json
package.json

- typescript
- jest
- testing library
- xstate

⬆️ Update dep

---

src/scss/utilities/_mixins.scss

MT-1147: Lower margin before content in disclosures

---

src/scss/global/_links.scss
src/scss/utilities/_mixins.scss

💄 MT-763 table of contents margin

---

src/scss/components/_table.scss
src/scss/utilities/_mixins.scss

- adjust cell text align top
- add more top margin for table

💄MT-476 Update styling table

---

src/svelte/CardArticle.svelte
src/svelte/CardArticle.test.ts
src/svelte/Link.svelte
src/svelte/Link.test.ts
src/svelte/Status.svelte
src/svelte/Status.test.ts
src/svelte/content/MenuItems.svelte
src/svelte/content/MenuItems.test.ts
src/svelte/content/RelatedLinksList.svelte
src/svelte/content/RelatedLinksList.test.ts
src/ts/utils.test.ts
src/ts/utils.ts
stories/Header.stories.svelte

🐛 MT-1161 fix external links

---

src/scss/components/_dropdown.scss
src/scss/global/_links.scss
src/svelte/content/MenuItems.svelte
src/svelte/content/MenuItems.test.ts

- move link in side list. For screen reader consistency
- MT-1213 increase font-size menu level 2 link
- add aria-current to current page link.

♿️ MT-1163 Fix a11y

---

src/scss/utilities/_grid.scss

💄MT-763 Fix grid for mobile

---

src/svelte/form/ExpandableInputList.svelte
src/svelte/form/ExpandableInputList.test.ts
src/svelte/form/Label.svelte
stories/components/form/ExpandableInputList.stories.svelte

MT-789 Fix

---

src/svelte/content/MenuItems.svelte

- to have different names on title and link

🐛 MT-1178 use content title

---

src/svelte/Dropdown.svelte

🐛 MT-1167 Close dropdown on link click

---

src/scss/global/_links.scss
src/svelte/content/MenuItems.svelte
stories/Header.stories.svelte

- remove flex styling from menu item
- update forward arrow end style
- update header story to show fix

💄 MT-1190 Fix styling menu right

---

src/scss/components/_dropdown.scss
src/scss/utilities/_layout.scss
stories/Header.stories.svelte

- should be as wide as fotter
- to make header, menu and footer same width

💄MT-1262 Remove padding header

---

src/svelte/content/MenuItems.svelte

MT-1284 Set rel externa for /dyr

---

src/scss/components/_dropdown.scss

- update menu bottom links to default no underline with underline on hover. To match other links in menu

💄MT-1278 Fix menu items active styling

---

src/scss/components/_disclosure.scss
stories/Disclosure.stories.svelte

- prevent icons being cut off
MT-1147

🎨 MT-1147 legislation box style adjustments

---

src/scss/components/_feedback-container.scss
stories/components/content/FeedbackBox.stories.svelte

💄MT-1328: Update placement for feedback box

---

src/scss/components/_multi-select.scss

MT-1373 Move rule to show links

---

src/scss/components/_buttons.scss
src/svelte/form/ExpandableInputList.svelte
src/svelte/form/MultiSelect.svelte
stories/components/Buttons.stories.svelte

- according to naming in Figma
- update button story

style: MT-812 rename flat button

---

src/svelte/DialogBox.svelte

MT-1365 Let animation be controlled by the components using the DS

---

src/scss/_print.scss

MT-1437 remove fant du box in print

---

src/svelte/DialogBox.svelte

- add ref to set focus on box after submit

Fix: MT-1333 focus on dialog box

---

src/scss/components/_disclosure.scss

Fix: MT-1436 sizing of table

---

src/scss/components/_feedback-container.scss
src/scss/components/_layout-with-sidebar.scss

💄 MT-1295: Position feedback box to not hide content on pages with wide text boxes.

---

src/svelte/FileUploadButton.svelte

- set button style to button secondary

Fix: MT-1165 upload button style

---

src/scss/_theme.scss
src/scss/components/_banner-image.scss
src/scss/components/_index.scss

MTP-486 adds css for banner image. With conditional breakpoint

---

package-lock.json
package.json
src/scss/components/_legal-collection.scss
stories/components/content/Collection.stories.svelte

Checkout branch and test that the webpack5 dep does not break anything

Fix: MTP-1189 fix table collection

---

src/scss/components/_menu-points.scss
src/scss/components/_top-tasks.scss
src/scss/global/_links.scss
src/scss/utilities/_grid.scss
src/svelte/MenuPoints.svelte
src/svelte/MenuPoints.test.ts
stories/components/MenuPoints.stories.svelte
stories/components/content/TopTasks.stories.svelte

MTP-1190_top_tasks_for_theme_pages

---

src/scss/components/_list.scss
src/scss/components/_menu-points.scss
src/scss/global/_links.scss
src/scss/global/_utils.scss
src/scss/utilities/_grid.scss
src/scss/utilities/_layout.scss
stories/components/Links.stories.svelte

MTP-480_navigasjonslenker_2_kolonner

---

src/svelte/components/form/ExpandableInputList.svelte
src/svelte/components/form/ExpandableInputList.test.ts
stories/components/form/ExpandableInputList.stories.svelte

MTP-47: fix show expanded list

---

src/scss/_theme.scss
src/scss/components/_task.scss
src/scss/global/_links.scss
src/scss/utilities/_mixins.scss
src/svelte/components/CardArticle.svelte
src/svelte/components/CardArticle.test.ts
src/svelte/content/HighlightedContentLink.svelte
stories/content/HighlightedLink.stories.svelte
stories/content/Task.stories.svelte

MTP-431_highlighted_link

---

src/scss/components/_top-tasks.scss
src/scss/global/_links.scss
src/scss/utilities/_grid.scss
src/svelte/components/Link.svelte
stories/components/Links.stories.svelte
stories/content/TopTasks.stories.svelte

MTP-1190 changed top tasks small to grid layout

---

stories/components/Links.stories.svelte

MTP-1288_greater_spacing_between_small_links

---

src/scss/components/_external-list.scss
src/scss/components/_index.scss
src/scss/components/_list.scss
src/svelte/components/Disclosure.svelte
stories/components/Disclosure.stories.svelte

MTP-39_list_of_lokaliteter

---

src/scss/global/_typography.scss

- will set m-t class on <main> element

MTP-1314: Remove top margin on main

---

src/svelte/components/form/MultiSelect.svelte

MTP-1295: Change to use mouseup event

---

src/scss/components/_breadcrumbs.scss
src/svelte/components/Breadcrumbs.svelte

MTP-452_last_page_should_not_be_a_link

---

src/scss/components/_buttons.scss
src/scss/global/_links.scss
src/svelte/components/CardArticle.svelte
src/svelte/components/CardArticle.test.ts
src/svelte/content/HighlightedContentLink.svelte
src/svelte/content/MenuItems.svelte
stories/components/Links.stories.svelte

MTP-546: Remove option to show <a> element as button.

---

src/scss/utilities/_layout.scss

- to fix focus for link in summary wizard result page

MTP-1173: add class for inline flex

---

src/scss/components/_expandable-input-list.scss
src/scss/global/_icon.scss
src/svelte/components/form/ExpandableInputList.svelte
src/svelte/components/form/TextInput.svelte
stories/visualStyle/Icons.stories.svelte

- align checkmark icon list baseline
- align expandable inputs

MTP-1173 design ajustments

---

src/scss/utilities/_grid.scss

MTP-1376: Add design for different column width

---

src/scss/utilities/_grid.scss

MTP-1165 QA make gap bigger

---

src/svelte/components/form/CheckboxWithSubSets.svelte
src/svelte/components/form/CheckboxWithSubSets.test.ts

MTP-1455 filter changes

---

src/scss/_theme.scss
src/scss/components/_breadcrumbs.scss
src/scss/components/_buttons.scss
src/scss/components/_dropdown.scss
src/scss/components/_file-upload-button.scss
src/scss/components/_form.scss
src/scss/components/_multi-select.scss
src/scss/components/_search.scss
src/scss/components/_summary-details.scss
src/scss/components/_tags.scss
src/scss/global/_links.scss
src/scss/utilities/_grid.scss
src/scss/utilities/_mixins.scss
src/svelte/components/form/Search.svelte
src/svelte/components/form/Search.test.ts
stories/components/form/Search.stories.svelte

- fix focus on items in header
- fix focus on breadcrumbs
- fix search outside of view on mobile

MTP-1473 focus remove search

---

mt-kit/core/css/src/components/_buttons.scss
mt-kit/core/css/src/components/_file-upload-button.scss
mt-kit/core/css/src/utilities/_layout.scss
src/scss/components/_buttons.scss
src/scss/components/_file-upload-button.scss
src/scss/utilities/_layout.scss
src/svelte/components/FileUploadButton.svelte

- use inclusively-hidden-initial to be able to make anchor link work.
- use clear button to be consistent with search clear
- update styles for long file names

MTP-1502: fix for upload

---

src/scss/components/_checkboxes-with-subsets.scss
src/scss/components/_index.scss
src/scss/global/_utils.scss
src/svelte/components/form/CheckboxWithSubSets.svelte
src/svelte/components/form/CheckboxWithSubSets.test.ts
stories/components/form/CheckboxWithSubSets.stories.svelte

MTP-1554: upgrade checkboxwithsubsets

---

src/svelte/components/form/CheckboxWithSubSets.test.ts

CheckboxWithSubsets.test missing closing )

Add missing parentheses in Checkbox test

---

src/scss/components/_layout-with-sidebar.scss

- Video goes over guide and covers guide-links

MTP-1449 Fix Embed video issue

---

src/scss/components/_layout-with-sidebar.scss

- Video covers aside menu
Note: 
**WIP** Go through all occurrences where z-index is used and replace with variables

MTP-1449 use z-index var on aside.expanded

---

mt-kit/core/css/src/components/_status.scss
mt-kit/core/svelte/src/lib/svelte/content/Status.svelte

Icon should align to first line of text

MTP-394 Fix Status li spacing and icon alignment

---

mt-kit/core/css/src/global/_icon.scss
mt-kit/core/css/src/global/_utils.scss
mt-kit/core/svelte/src/lib/svelte/components/Published.svelte

use with https://github.com/Mattilsynet/mattilsynet-web/pull/550

MTP-1666 mtp 1657 svelte part for a vise liste av regelverksprosesser pa en temaside

---

mt-kit/core/svelte/src/lib/svelte/components/Published.svelte

update default lang code from `NO-nb` to `nb`

MTP-1724 Change lang code from NO-nb to nb

---

mt-kit/core/css/src/components/_file-upload-button.scss
mt-kit/core/css/src/components/_form.scss
mt-kit/core/svelte/src/lib/svelte/components/FileUploadButton.svelte

- fix spacing between upload and button

MTP-1827: fix focus fileupload

---

mt-kit/core/css/src/global/_body.scss
mt-kit/core/css/src/utilities/_layout.scss

fixes horizontal scroll caused by footer width and flex direction of child elements on breakpoint

MTP-1886 Fix footer scroll and flex direction on child elements

---

mt-kit/core/css/src/global/_icon.scss
mt-kit/core/svelte/src/lib/svelte/content/MenuItems.svelte

- for a11y to indicate interactive element

MTP-1830: add arrow after link in menu

---

mt-kit/core/css/src/_theme.scss
mt-kit/core/css/src/components/_fieldset.scss

increase spacing between fieldset and error border

MTP-1879 designjusteringer for lansering

---

mt-kit/core/css/src/_color-token-contrast.md
mt-kit/core/css/src/_color-tokens.scss
mt-kit/core/css/src/utilities/colors.js

MTP-1830: update mellombeige

---

mt-kit/core/css/src/_print.scss
mt-kit/core/css/src/_reset.scss
mt-kit/core/css/src/components/_article.scss
mt-kit/core/css/src/components/_dropdown.scss
mt-kit/core/css/src/components/_image.scss
mt-kit/core/css/src/components/_layout-with-sidebar.scss
mt-kit/core/css/src/components/_legal-collection.scss
mt-kit/core/css/src/components/_menu-points.scss
mt-kit/core/css/src/components/_multipage-form.scss
mt-kit/core/css/src/components/_summary-details.scss
mt-kit/core/css/src/global/_links.scss
mt-kit/core/css/src/global/_typography.scss
mt-kit/core/css/src/utilities/_mixins.scss
mt-kit/core/svelte/src/lib/svelte/components/Dropdown.svelte
mt-kit/core/svelte/src/lib/svelte/components/SummaryDetail.svelte
mt-kit/core/svelte/src/lib/svelte/components/form/ExpandableInputList.svelte
mt-kit/core/svelte/src/lib/svelte/content/HighlightedContentLink.svelte
mt-kit/core/svelte/src/lib/svelte/content/MenuPointsIcons.svelte
mt-kit/core/svelte/src/stories/nettlosninger/Article.stories.svelte
mt-kit/core/svelte/src/stories/nettlosninger/Guide.stories.svelte
mt-kit/core/svelte/src/stories/visualStyle/Spacing.stories.svelte

- figure, img
- details summary
- aside
- strong

Mtp 1827 bruke riktige variabler i ds other

---

mt-kit/core/css/src/components/_breadcrumbs.scss

MTP-1830: fix breadcrumbs

---

mt-kit/core/svelte/src/lib/svelte/content/FactsQuestionsAnswers.svelte

MTP-1830: add .mt classes

---

mt-kit/core/svelte/src/lib/svelte/components/Breadcrumbs.svelte
mt-kit/core/svelte/src/lib/ts/index.ts
mt-kit/core/svelte/src/lib/ts/types.d.ts
mt-kit/core/svelte/src/stories/Breadcrumbs.stories.svelte

- extract Link interface. Use url and text as other links

MTP-2027: refac breadcrumbs #minor

---

mt-kit/core/svelte/src/lib/svelte/components/ChapterMenu.svelte

This reverts commit 1e4ece06ae97b740eafb643311f34324c3aafc44.

Revert "MTP-2008 add boolean check for hiding subchapters (#1001)"

---

mt-kit/core/css/src/_color-token-contrast.md
mt-kit/core/css/src/_color-tokens.scss
mt-kit/core/css/src/global/_body.scss
mt-kit/core/css/src/global/_links.scss
mt-kit/core/css/src/utilities/colors.js

- better separation of concern

MTP-2046: refac link--button

---

mt-kit/core/svelte/src/lib/svelte/components/map/Map.svelte
mt-kit/core/svelte/src/lib/ts/mapUtils.ts

- to prevent zooming outside map

MTP-2079: add minZoom

---

mt-kit/core/svelte/src/lib/ts/mapUtils.ts

- to show all of Norway on initial load on mobil

MTP-2080: update zoom and center

---

mt-kit/core/css/src/components/_map.scss

MTP-2088: update border radius

---

mt-kit/core/css/src/components/_published.scss
mt-kit/core/svelte/src/stories/Published.stories.svelte

- to display two dates under each other

MTP-2104: add stylign for meta-rows

---

mt-kit/core/css/src/global/_utils.scss

-for spacing in detaljert information blåskjell

MTP-2114: add util

---

mt-kit/core/css/src/components/_layout-with-sidebar.scss

Designers wants bigger font to emphasize hierarchy of it being the title of the guide

MTP-1677 Guide title increase font size

---

mt-kit/core/svelte/src/lib/svelte/components/Dropdown.svelte
mt-kit/core/svelte/src/lib/svelte/components/form/Search.svelte
mt-kit/core/svelte/src/stories/Header.stories.svelte

pass open state to slot and call focus if true

MTP-2183 focus search when dropdown opens

---

mt-kit/core/css/src/components/_form.scss
mt-kit/core/svelte/src/lib/svelte/components/form/Checkbox.svelte

- add bold for search filter checkboxes

MTP-2143: add option to pass class to legend

---

mt-kit/core/css/src/components/_pagination.scss
mt-kit/core/css/src/global/_links.scss

All page numbers gets circle on hover
Increase padding on next/previous buttons + border radius
Increase spacing between pagination and last result
Change hover background color on results

Mtp 2211 designjusteringer

---

mt-kit/core/svelte/src/lib/svelte/components/Dropdown.svelte
mt-kit/core/svelte/src/stories/Header.stories.svelte

MTP-2205 close dropdown on submit

---

mt-kit/core/css/src/components/_expandable-input-list.scss
mt-kit/core/css/src/components/_form.scss
mt-kit/core/css/src/global/_body.scss

adjust spacing (padding) around help text and above expandable input list

MTP-2241 Adjust form spacing

---

mt-kit/core/css/src/_color-token-contrast.md
mt-kit/core/css/src/_color-tokens-new.scss
mt-kit/core/css/src/_color-tokens.scss
mt-kit/core/css/src/components/_list.scss
mt-kit/core/css/src/global/_body.scss
mt-kit/core/css/src/global/_utils.scss
mt-kit/core/css/src/utilities/colors.js
mt-kit/core/svelte/src/lib/svelte/components/ListOfDescriptionLists.svelte
mt-kit/core/svelte/src/stories/ListOfDescriptionLists.stories.svelte

design task: [MTP-2347](https://mattilsynet.atlassian.net/browse/MTP-2347)
[MTP-2347]: https://mattilsynet.atlassian.net/browse/MTP-2347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MTP-2315 frontend for tabell fra tredjepart data

---

mt-kit/core/svelte/src/lib/svelte/components/FormSteps.svelte
mt-kit/core/svelte/src/lib/svelte/components/FormSteps.test.ts
mt-kit/core/svelte/src/lib/ts/types.d.ts
mt-kit/core/svelte/src/stories/FormSteps.stories.svelte

- logikk for a sette opp ny side fra betingelse

MTP-2332 use currentPath over completed to calculate steps #minor

---

mt-kit/core/css/src/components/_form-steps.scss
mt-kit/core/css/src/global/_body.scss

MTP-2401: update styling for form steps

---

mt-kit/core/css/src/_theme.scss
mt-kit/core/css/src/global/_links.scss
mt-kit/core/svelte/src/lib/svelte/content/HighlightedContentLink.svelte
mt-kit/core/svelte/src/lib/svelte/content/HighlightedContentLink.test.ts
mt-kit/core/svelte/src/stories/nettlosninger/HighlightedContentLink.stories.svelte

added $transition-ms-... variables to use for smoother background-color transitions

MTP-2407 fremhevet innhold endringer

---

mt-kit/core/css/src/global/_links.scss

Remove all places padding-left is used on hover links and Disclosures etc.

MTP-2392 remove padding-left on hover

---

mt-kit/core/svelte/src/lib/svelte/components/form/Checkbox.svelte
mt-kit/core/svelte/src/lib/svelte/components/form/RadioGroup.svelte
mt-kit/core/svelte/src/lib/svelte/components/form/Select.svelte
mt-kit/core/svelte/src/lib/svelte/components/form/TextInput.svelte

- to be able to remove the optional

MTP-2559: add showOptionalText

---

mt-kit/core/css/src/components/_breadcrumbs.scss
mt-kit/core/css/src/global/_links.scss
mt-kit/core/svelte/src/lib/svelte/components/SearchResult.svelte
mt-kit/core/svelte/src/stories/Breadcrumbs.stories.svelte
mt-kit/core/svelte/src/stories/Links.stories.svelte

ellipsis is now working for the last crumb, but its a problem with the second last, cause of the wrapper styles causes the text/icon to be shrinked down and hidden when scaling down the window

MTP-2506 breadcrumbs fix and searchresult crumbs align

---

mt-kit/core/css/src/components/_dropdown.scss
mt-kit/core/svelte/src/lib/svelte/content/MenuItems.svelte
mt-kit/core/svelte/src/stories/Header.stories.svelte

Links on right side in Menu has wrong font-size (28px), should be 24px on desktop and 21 on mobile. Bottom and right side should always be the same.
split up styles between disclosures and normal links which is not disclosures and doesnt have icon svgs

MTP-2570 lenkene pa hoyresiden har feil font str

---

mt-kit/core/svelte/src/lib/svelte/components/Disclosure.svelte
mt-kit/core/svelte/src/lib/svelte/components/Disclosure.test.svelte
mt-kit/core/svelte/src/lib/svelte/components/Disclosure.test.ts

MTP-2637: remove xstate for disclosure

---

mt-kit/core/css/package.json
mt-kit/core/css/src/_theme.scss
mt-kit/core/css/src/components/_breadcrumbs.scss
mt-kit/core/css/src/components/_buttons.scss
mt-kit/core/css/src/components/_disclosure.scss
mt-kit/core/css/src/components/_dropdown.scss
mt-kit/core/css/src/components/_form-intro.scss
mt-kit/core/css/src/components/_legal-text.scss
mt-kit/core/css/src/components/_menu-points.scss
mt-kit/core/css/src/components/_notice.scss
mt-kit/core/css/src/components/_summary-details.scss
mt-kit/core/css/src/global/_links.scss
mt-kit/core/css/src/global/_typography.scss
mt-kit/core/css/src/utilities/_functions.scss
mt-kit/core/css/src/utilities/_layout.scss
mt-kit/core/css/src/utilities/_mixins.scss
mt-kit/core/svelte/package-lock.json
mt-kit/core/svelte/package.json

deprecation warning about Legacy JS api is fixed in `svelte-preprocess 6.0.3`
explained here
https://github.com/sveltejs/svelte-preprocess/blob/main/CHANGELOG.md

MTP-2769 fix console warnings after upgrading sass

---

mt-kit/core/svelte/src/lib/svelte/components/form/RadioGroup.svelte

Too ambitious when cleaning warnings, this topic will have to be addressed when we have uu-hat on later instead

MTP-2803 Revert use of required on radio as it prevents submit

---

mt-kit/core/svelte/package-lock.json
mt-kit/core/svelte/package.json

Version 0.3.8 of design fixes overflow, placement and animation of dialog box, that's needed for cookie consent dialog to work properly

feat: bump MT design dep
