package.json, src/scss/components/_form.scss, src/scss/utilities/_mixins.scss, stories/components/form/AllForm.stories.svelte
- add label error style only to checkbox and radio. Remove from input.
- update style on radio and checkbox border. To match Figma
- update style on input error border. To match Figma
- Add story to display all styled inputs
Relates to MT-337
=> Fix wrong styling on error

src/scss/components/_article.scss, stories/components/content/Article.stories.svelte
Remove hard coded styles for <figure> in article.
Relates to: MT-388
=> Use grid system for Article figure

src/scss/components/_breadcrumbs.scss, src/svelte/Breadcrumbs.svelte
On mobile: 
- Only previous breadcrumb should be displayed. Arrow points left. Smaller spacing between arrow and text.
MT-1009, MT-945
=> 💄MT-1009 adjust breadcrumbs mobile

src/scss/components/_dropdown.scss
- only apply hover underline to button link (menu trigger button)
=> MTP-1214: fix remove underline on hover menu

src/scss/components/_buttons.scss, src/svelte/components/ButtonSpinner.svelte
- removed if statements to fix SR status update
- Changed class on span to class:spinner={inProgress}
- spinnerPlacement uses class with flexbox
- SR reads aria labels on WIN
The SR works fine on my end (except in IE), using a HP ZBook, WIN 11. Tested with NVDA, Jaws and Windows Narrator on Chrome, Edge, Firefox and IE(in Edge).
=> MTP-1491 Fix ariaLabel status

src/svelte/components/form/CheckboxWithSubSets.test.ts
Why is that parentheses still missing? I thought we fixed it once already.
@lha047
=> Fix CheckboxWithSubSets.test missing parentheses

src/scss/components/_notice.scss
Notice box width should follow the rest of the content and use same width
Task: 
https://mattilsynet.atlassian.net/browse/MTP-206
=> MTP-206 Remove Notice margins fix

mt-kit/core/css/src/components/_page-summary.scss
This fixes the issue where the anchor tag with text "Endre" breaks on the summary-step forms.
=> MTP-1681 Fix summarypage anchor breaks

mt-kit/core/css/src/components/_search.scss
=> MTP-2006-juster-sokefeltet-slik-at-knappen-vokser-etter-teksten-i-seg

mt-kit/core/svelte/src/lib/svelte/components/map/Map.svelte
- to try to prevent interaction with map without focus on map on touch
=> MTP-2072: set focus only on interactions

mt-kit/core/css/src/components/_disclosure.scss, mt-kit/core/css/src/components/_summary-details.scss, mt-kit/core/svelte/src/lib/svelte/components/SummaryDetail.svelte
:not([href]) check before using mixing on .disclosure-header, to exclude if it is a link
Add extra class to not cause issue for other places mt-summary is used
Mixin is moved from:
.mt-summary -> &.mt-summary-icon
=> MTP-2442 add rule for disclosures used as link, move mt-summary logic

mt-kit/core/css/src/components/_layout-with-sidebar.scss
fixes the issue where ::before element is treated as grid item
=> MTP-2438 Fix for disclosure in layout-with-sidebar

mt-kit/core/svelte/src/lib/svelte/components/form/Checkbox.svelte, mt-kit/core/svelte/src/lib/svelte/components/form/Checkbox.test.ts, mt-kit/core/svelte/src/lib/ts/index.ts, mt-kit/core/svelte/src/lib/ts/types.d.ts, mt-kit/core/svelte/src/lib/ts/utils.ts, mt-kit/core/svelte/src/stories/form/Checkbox.stories.svelte
- to avoid rerender when value is undefined
- dispatching custom event for previous onChange event
=> MTP-2493: update checkbox

mt-kit/core/css/src/components/_page-summary.scss
- fix content "outside" layout
- From this ![Screenshot 2024-09-13 at 14 30 55](https://github.com/user-attachments/assets/95bf9fd5-2736-4424-a762-cba5c36e78f0)
- to this
=> MTP-2495: fix summary layout summary

mt-kit/core/svelte/src/lib/svelte/content/MenuPointsIcons.svelte, mt-kit/core/svelte/src/lib/svelte/content/MenuPointsIcons.test.ts, mt-kit/core/svelte/src/lib/ts/types.d.ts, mt-kit/core/svelte/src/stories/nettlosninger/MenuPoints.stories.svelte
Changes: Remove the themepage intro as fallback.
Results: If themepage has no keywords added, then nothing will show on the MenuPoint Card (link to themepage)
=> MTP-2462 Remove keywords fallback on MenupointsIcons

mt-kit/core/css/src/utilities/_mixins.scss
- content designers say we should not use italic for this.
=> MTP-2651: remove special styling on card-article intro

mt-kit/core/svelte/src/lib/svelte/components/form/CheckboxWithSubSets.svelte, mt-kit/core/svelte/src/lib/svelte/components/form/CheckboxWithSubSets.test.ts, mt-kit/core/svelte/src/stories/form/CheckboxWithSubSets.stories.svelte
Also fixed error with 3rd level options children: when no js is loaded they weren't shown until click, but should be permanently shown just like level 1 and 2
=> MTP-2803 Refactored loadJs check in CheckboxWithSubSets

mt-kit/core/svelte/package-lock.json, mt-kit/core/svelte/package.json
Apparently svelte > 5 is needed as a peerDependency, for component prop type info to be included in the published package. Ref https://github.com/sveltejs/kit/issues/12972
With this, the web-project "sees" what type of props the designsystem components have and should have, eliminating the lint errors of type "xxx is not assignable to type never"
=> MTP-2803 config to include component prop types in package

mt-kit/core/css/src/_color-tokens-new.scss, mt-kit/core/css/src/_reset.scss, mt-kit/core/css/src/_theme.scss, mt-kit/core/css/src/app.scss, mt-kit/core/css/src/global/_body.scss, mt-kit/core/svelte/package.json
- ✅ Tiny cleanup of empty `_fonts.scss` file
- ✅ Letting `@mattilsynet/design` set font-family, background and color
- ✅ Keeping local `color-mt-text-dark` for now as it is used in several components
- 🤔 Question: There is a `data-theme="green"`, but from what I can see, it is only used once; is this something we should just move into `mt-body` maybe?
=> fix(MTP-2782): use text color granskog and font mattilsynet sans

mt-kit/core/svelte/src/lib/svelte/components/form/RadioGroup.svelte, mt-kit/core/svelte/src/lib/svelte/components/form/RadioGroup.test.ts, mt-kit/core/svelte/src/stories/form/RadioButtons.stories.svelte
- Removed `theme="button"` as this was not in use, and can easily be created by `Chip` from `@mattilsynet/design` if needed later on
=> MTP-2978 radio input
